# Generated by Django 2.1.15 on 2020-07-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_qr_visiting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qr',
            name='store',
        ),
        migrations.AlterField(
            model_name='visiting',
            name='visiting_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Qr',
        ),
    ]
