# Generated by Django 2.1.15 on 2020-06-23 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('num', models.CharField(max_length=100)),
                ('addr', models.CharField(max_length=1000)),
                ('hour', models.DateTimeField()),
                ('service', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='map',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='effects.Store'),
        ),
    ]
