# Generated by Django 2.1.15 on 2020-07-04 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('num', models.CharField(max_length=100)),
                ('addr', models.CharField(max_length=500)),
                ('open_hour', models.TimeField()),
                ('closed_hour', models.TimeField()),
                ('service', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Visiting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visiting_time', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.Store')),
            ],
        ),
    ]
